--- 
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2 
      state: present

  - name: i want to start web serevr apache2
    service:
       name: apache2
       state: started